version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src  # Montage du code pour le développement
      - ./public:/app/public
    restart: unless-stopped