name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]  # Déclenche aussi sur les tags versionnés

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/mumu696/devops-ninja:latest
          ghcr.io/mumu696/devops-ninja:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/mumu696/devops-ninja:latest
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'