name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Generate coverage badge
      run: npx jest-coverage-badges
    
    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: coverage-badge.svg